name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Cache clojure deps
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ~/.m2/repository
        key: ${{ hashFiles('project.clj') }}

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: lein deps

    - name: Run tests
      run: lein test
